import React from 'react';

const About = () => {
  return (
      <div className='text-lg font-bold flex flex-start flex-wrap'>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
         <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
         <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
         <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
		 <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
        <div>About</div>
      </div>
  );
};

export default About;