"use client";

import "./globals.css";

import Head from "next/head";
import Link from "next/link";
import Image from "next/image"
import { useState } from "react";
import { FaBars } from "react-icons/fa";
import { GrClose } from "react-icons/gr";
import { useMedia } from "react-use";

// Menu
const menuItems = [
  {
    menu: "Saint John's Page",
    link: "/",
  },
  {
    menu: "About",
    link: "/about",
  },
  // {
  //   menu: "Product",
  //   link: "/product",
  // },
  // {
  //   menu: "Services",
  //   link: "/services",
  // },
  {
    menu: "You May Contact Me",
    link: "/contact",
  },
];

export default function RootLayout({ children }) {
  const displayMenu = () => {
    return menuItems.map((item) => (
      <Link
        key={item.menu}
        href={item.link}
        className="pb-5 hover:text-yellow md:pb-0 md:pl-6"
      >
        {item.menu}
      </Link>
    ));
  };

  const isDesktop = useMedia("(min-width: 768px)", true);
  const [open, setOpen] = useState(false);

  const toggleSidebar = () => setOpen(!open);

  return (
    <html>
      <body className="mb-16">
        <Head>
          <title>Next & Tailwind Sidebar</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
       

        <div className="flex flex-col justify-center flex-wrap">
        
       

        {/* <div className="theGrid grid- grid-cols-1- lg:grid-cols-[2fr_1fr]- gap-4- p-4">  */}
        <div className="theGrid-">
          
        <div className="h-[100vh]- p-1">
          {children}
        </div>
          
          <div className="lg:block lg:h-[100vh] p-4 mt-8">
           
            <div className="border-b-2">
              <a href="https://www.usccb.org/resources/2024cal.pdf">Liturgical Calendar</a>
            </div>

          </div>

         

        </div>
        </div>
        

      </body>
    </html>
  );
}
