"use client";

import "./globals.css";

import Head from "next/head";
import Link from "next/link";
import Image from "next/image"
import { useState } from "react";
import { FaBars } from "react-icons/fa";
import { GrClose } from "react-icons/gr";
import { useMedia } from "react-use";

// Menu
const menuItems = [
  {
    menu: "Saint John's Page",
    link: "/",
  },
  {
    menu: "About",
    link: "/about",
  },
  // {
  //   menu: "Product",
  //   link: "/product",
  // },
  // {
  //   menu: "Services",
  //   link: "/services",
  // },
  {
    menu: "You May Contact Me",
    link: "/contact",
  },
];

export default function RootLayout({ children }) {
  const displayMenu = () => {
    return menuItems.map((item) => (
      <Link
        key={item.menu}
        href={item.link}
        className="pb-5 hover:text-yellow md:pb-0 md:pl-6"
      >
        {item.menu}
      </Link>
    ));
  };

  const isDesktop = useMedia("(min-width: 768px)", true);
  const [open, setOpen] = useState(false);

  const toggleSidebar = () => setOpen(!open);

  return (
    <html>
      <body className="mb-16">
        <Head>
          <title>Next & Tailwind Sidebar</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <div className="flex justify-between p-2 shadow-lg items-center">
            {/* Logo */}
            <div>
              {/* <Image src={Logo} alt='Logo' width={100} height={100} /> */}
            </div>

            {/* Menu links */}
            <div className="">
              <div className="text-red">
                {isDesktop ? (
                  displayMenu()
                ) : (
                  <>
                    <button
                      className="border-none bg-none"
                      onClick={() => toggleSidebar()}
                    >
                      <FaBars />
                    </button>
                    <div
                      className={
                        open
                          ? "absolute top-0 right-0 z-50 h-screen w-3/5 bg-white shadow-md"
                          : "hidden"
                      }
                    >
                      <div className="flex flex-col text-center">
                        <button
                          className="mb-7 mt-7 mr-1 flex justify-end px-5 text-xl"
                          onClick={() => toggleSidebar()}
                        >
                          <GrClose />
                        </button>
                        {displayMenu()}
                      </div>
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>

        <div>
        <div className="flex flex-col justify-center flex-wrap">
        
        <div className="h-96 lg:h-48">
          <div className="flex flex-row flex-wrap justify-between">
            <div>
              <Image
                width="50"
                height="50"
                className="m-4 w-48 h-48 rounded-full"
                src="/mary-with-jesus-2.png"
                alt="jesus"
              ></Image>
            </div>
            <div>
              <Image
                width="50"
                height="50"
                className="m-4 w-48 h-48 rounded-full"
                src="/jesus-christ-3.webp"
                alt="jesus"
              ></Image>
            </div>
            <div>
              <Image
                width="50"
                height="50"
                className="m-4 w-48 h-48- rounded-full"
                src="/jesus-christ-1.webp"
                alt="cross"
              ></Image>
            </div>
            <div>
              <Image
                width="50"
                height="50"
                className="m-4 w-48 h-48 rounded-full"
                src="/angel2sm.png"
                alt="angel"
              ></Image>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[850px_1fr] gap-4 p-4">

        <div className="h-[100vh]- p-1">{children}</div>
          
          <div className="lg:block lg:h-[100vh] p-4 mt-8">
            <div className="border-b-2">
              <Link href="/kjv">Holy Bible, KJV</Link>
            </div>
            <div className="mt-4 mb-4 font-bold italic underline">
              <h1>
                Catholic Christian Church Saints, Magazines, Websites, Reviews
                and Movies
              </h1>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.americamagazine.org/"
                target="_blank"
              >America Magazine, The Jesuit Review</a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.archphila.org"
                target="_blank"
              >
                Archphila
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://adoremus.org/"
                target="_blank"
              >
                Adoremus
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://angeluspress.org/products/the-angelus-magazine-international-1-year-subscription"
                target="_blank"
              >
                Angelus Press
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/saint-bernadette-movie">
                Bernadette, Saint, Movie
              </Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.biblegateway.com"
                target="_blank"
              >
                Bible Gateway
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/cloisteredlife1">
                Carmelites of the Carmel of Mary
              </Link>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.gettyimages.com/search/2/image?page=5&phrase=largest%20cathedrals%20in%20the%20world&sort=mostpopular&license=rf%2Crm"
                target="_blank"
              >
                Cathedrals, Beautiful
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/cathedrals-largest">Cathedrals, Largest</Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholic.org"
                target="_blank"
              >
                Catholic
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.usccb.org"
                target="_blank"
              >
                Catholic Bishops, Conference of USA
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.aboutcatholics.com"
                target="_blank"
              >
                Catholics, About
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholiccity.com"
                target="_blank"
              >
                Catholic City
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholic.org/encyclopedia"
                target="_blank"
              >
                Catholic Encyclopedia
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.ewtn.com"
                target="_blank"
              >
                Catholic EWTN
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://subscribe-renew.com/us-catholic-magazine"
                target="_blank"
              >
                Catholic Magazine USA
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholic-mass-time.com"
                target="_blank"
              >
                Catholic Mass Time
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.lighthousecatholicmedia.org"
                target="_blank"
              >
                Catholic Media, Light House
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.mycatholic.com"
                target="_blank"
              >
                Catholic, My
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholicnews.com"
                target="_blank"
              >
                Catholic News
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.srol.org/assets/Adult-Faith-Formation/Prominent-Catholic-Periodicals.pdf"
                target="_blank"
              >
                Catholic Periodicals, Prominent
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.liguori.org"
                target="_blank"
              >
                Catholic Publication
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.ncregister.com/topic/pope-francis"
                target="_blank"
              >
                Catholic Register, National
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/ourladyofpeaceinhonolulu">
                Catholic Shrine Basilica of Our Lady of Peace in Honolulu Hawaii
              </Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.thecatholictelegraph.com/RK=2/RS=ypciuBU4YN77MVuYEMJNf0MVl.c-"
                target="_blank"
              >
                Catholic Telegraph
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.liguori.org/catholic-update"
                target="_blank"
              >
                Catholic Update
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.USCatholic.org"
                target="_blank"
              >
                Catholic, USA
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholicworldreport.com"
                target="_blank"
              >
                Catholic World Report
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.christlife.org"
                target="_blank"
              >
                Christ Life
              </a>
            </div>
           
            <div className="border-b-2">
              <Link href="/christmas-angels">Christmas Angels</Link>
            </div>
            <div className="border-b-2">
              <Link href="/cloisteredlife-directory">Cloistered Life</Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.chnetwork.org"
                target="_blank"
              >
                Coming Home Network
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.usccb.org"
                target="_blank"
              >
                Conference of Catholic Bishops USA
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/saint-marianne-cope">Cope, Marianne, Saint</Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.crisismagazine.com"
                target="_blank"
              >
                Crisis Magazine
              </a>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.franciscanmedia.org/franciscan-spirit-blog/top-catholic-magazines/"
                target="_blank"
              >
                Franciscan Media
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/gospel-of-john-movie"> Gospel of John, Movie</Link>
            </div>
            <div className="border-b-2">
              <a href="https://www.hprweb.com/" target="_blank">
                Homiletic Pastoral Review
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://insidethevatican.com/"
                target="_blank"
              >
                Inside The Vatican
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://keepthefaith.org/latin-mass/"
                target="_blank"
              >
                Keep the Faith Latin Mass/
              </a>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.loamagazine.org"
                target="_blank"
              >
                Loa Magazine
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.magnificat.net"
                target="_blank"
              >
                Magnificat
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/saint-mary-mazzarello">
                Mazzarello, Mary, Saint, Movie
              </Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.newadvent.org"
                target="_blank"
              >
                New Advent
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.newoxfordreview.org"
                target="_blank"
              >
                New Oxford Review
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.osv.com/"
                target="_blank"
              >
                Our Sunday Visitor
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/queens-funeral">
                Queen of England Funeral Procession
              </Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.stmarysmessenger.com"
                target="_blank"
              >
                Saint Marys Messenger
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/sister-servants-of-the-holy-spirit">
                Sister Servants of the Holy Spirit of Perpetual Adoration
              </Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.spiritdaily.com"
                target="_blank"
              >
                Spirit Daily
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://upfaithandfamily.com/"
                target="_blank"
              >
                Up Faith And Family
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.VaticanNews.va/enhtml"
                target="_blank"
              >
                Vatican News
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://thewandererpress.com/"
                target="_blank"
              >
                Wanderer Press
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.wau.org"
                target="_blank"
              >
                Word Amoung Us
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.wordonfire.org"
                target="_blank"
              >
                Word On Fire
              </a>
            </div>
          </div>

          {/* <div className="order-1 h-[100vh] p-1">{children}</div> */}

        </div> {/* grid */}
        </div>
        </div>

      </body>
    </html>
  );
}
