"use client";

import "./globals.css";

import Head from "next/head";
import Link from "next/link";
import Image from "next/image"
import { useState } from "react";
import { FaBars } from "react-icons/fa";
import { GrClose } from "react-icons/gr";
import { useMedia } from "react-use";

// Menu
const menuItems = [
  {
    menu: "Saint John's Page",
    //link: "/",
  },
  {
    menu: "About",
    //link: "/about",
  },
  // {
  //   menu: "Product",
  //   link: "/product",
  // },
  // {
  //   menu: "Services",
  //   link: "/services",
  // },
  {
    menu: "You May Contact Me",
    //link: "/contact",
  },
 
];



export default function RootLayout({ children }) {
  const displayMenu = () => {
    
    return menuItems.map((item,i) => (
      <div key={i} className="mr-4">{item.menu}</div>
     
    ));
    
  };

  const isDesktop = useMedia("(min-width: 768px)", true);
  const [open, setOpen] = useState(false);

  const toggleSidebar = () => setOpen(!open);

  return (
    <html>
      <body className="mb-16">
        <Head>
          <title>For Jesus Christ</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
       
        <div className="flex flex-col justify-center flex-wrap">
        
        <div className="h-96 lg:h-48">
     
          <div className="flex flex-row flex-wrap justify-between">
            <div>
              <Image
                width="50"
                height="50"
                className="m-4 w-48 h-48 rounded-full"
                src="/mary-with-jesus-2.png"
                alt="jesus"
              ></Image>
            </div>

            <div>
              <Image
                width="50"
                height="50"
                className="m-4 w-48 h-48 rounded-full"
                src="/jesus-christ-3.webp"
                alt="jesus"
              ></Image>
            </div>
            <div>
              <Image
                width="50"
                height="50"
                className="m-4 w-48 h-48- rounded-full"
                src="/jesus-christ-1.webp"
                alt="cross"
              ></Image>
            </div>
            <div>
              <Image
                width="50"
                height="50"
                className="m-4 w-48 h-48 rounded-full"
                src="/angel2sm.png"
                alt="angel"
              ></Image>
            </div>
          </div>
        </div>

        <div className="grid-not-working-causing-wrong-links grid-cols-1- lg:grid-cols-[850px_1fr]- gap-4- p-4-">

        <div className="h-[100vh]- p-1">{children}</div>
          
          <div id="section1" className="lg:block lg:h-[100vh] p-4 mt-8">
            
            {/* <div className="border-b-2">
              <Link href="/kjv" target="_blank">Holy Bible, KJV</Link>
            </div> */}

            <div className="border-b-2">
              <Link href="https://www.usccb.org/resources/2024cal.pdf" target="_blank">Liturgical Calendar</Link>
            </div>
            <div className="border-b-2- mb-6 border-b-2- border-gray-500">
              <a
                className="flex flex-wrap text-blue-500-"
                href="https://willowy-beijinho-1d8105.netlify.app/"
                target="_blank"
              >
              Precious Nuns and Convents Index</a>
            </div>
            <div className="mt-4 mb-4 font-bold italic underline">
              <h1>
                Catholic Christian Church Saints, Magazines, Websites, Reviews
                and Movies
              </h1>
            </div>
           
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://adoremus.org/"
                target="_blank"
              >
                Adoremus
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.americamagazine.org/"
                target="_blank"
              >America Magazine, The Jesuit Review</a>
            </div>
           
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://angeluspress.org/products/the-angelus-magazine-international-1-year-subscription"
                target="_blank"
              >
                Angelus Press
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.archphila.org"
                target="_blank"
              >
                Archdiocese of Philadelphia
              </a>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://writersdepart.com/uploads/rule-of-st-benedict.pdf"
                target="_blank"
              >
                Monastery. Benedictine Rule for Service
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/saint-bernadette-movie">
                Bernadette, Saint, Movie
              </Link>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.biblegateway.com"
                target="_blank"
              >
                Bible Gateway
              </a>
            </div>
           
            <div className="border-b-2">
              <Link href="/cloisteredlife1">
                Carmelites of the Carmel of Mary
              </Link>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.gettyimages.com/search/2/image?page=5&phrase=largest%20cathedrals%20in%20the%20world&sort=mostpopular&license=rf%2Crm"
                target="_blank"
              >
                Cathedrals, Beautiful
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/cathedrals-largest">Cathedrals, Largest</Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholic.org"
                target="_blank"
              >
                Catholic
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://simple.wikipedia.org/wiki/Pope_Francis"
                target="_blank"
              >
                Catholic, Pope Francis, wikipedia.com
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.google.com/search?q=pope+francis+birth+name&oq=Pope+Francis+birth+name&gs_lcrp=EgZjaHJvbWUqDAgAEAAYRhj7ARiABDIMCAAQABhGGPsBGIAEMggIARAAGBYYHjIICAIQABgWGB4yCAgDEAAYFhgeMggIBBAAGBYYHjIICAUQABgWGB4yCAgGEAAYFhgeMg0IBxAAGIYDGIAEGIoFMg0ICBAAGIYDGIAEGIoFMg0ICRAAGIYDGIAEGIoF0gEJODk3OWowajE1qAIIsAIB&sourceid=chrome&ie=UTF-8#vhid=gvd07n-j9Vt94M&vssid=l"
                target="_blank"
              >
                Catholic, Pope Francis birth name
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://beajesuit.org/"
                target="_blank"
              >
                Catholic, Jesuit, School to become
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://en.wikipedia.org/wiki/List_of_current_cardinals"
                target="_blank"
              >
                Catholic, Cardinals, List of Current, Wikipedia.com
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.ncronline.org/news/bishops-united-states-basics#:~:text=More%20than%20a%20third%20(168,bishops%20and%2076%20auxiliary%20bishops."
                target="_blank"
              >
                Catholic, Bishops, National Catholic Register, United States
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholicworldreport.com/2025/02/17/diocesan-priestly-vocations-in-the-u-s-a-look-at-the-numbers/"
                target="_blank"
              >
                Catholic, Diocesan Priestly Vocations, a look at the numbers, Catholic World Report
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.ncronline.org/news/demographic-forces-beyond-hierarchical-control-are-changing-us-church"
                target="_blank"
              >
                Catholic, Demographic Forces, National Catholic Register
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.youtube.com/watch?v=bBDjnjP_XK0"
                target="_blank"
              >
                Catholic, Gaza, The Catholic Church there
              </a>
            </div>
			
			    <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.aboutcatholics.com"
                target="_blank"
              >
                Catholics, About
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.usccb.org"
                target="_blank"
              >
                Catholic Bishops, Conference of USA
              </a>
            </div>
        
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholiccity.com"
                target="_blank"
              >
                Catholic City
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholic.org/encyclopedia"
                target="_blank"
              >
                Catholic Encyclopedia
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.ewtn.com"
                target="_blank"
              >
                Catholic EWTN
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://subscribe-renew.com/us-catholic-magazine"
                target="_blank"
              >
                Catholic Magazine USA
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholic-mass-time.com"
                target="_blank"
              >
                Catholic Mass Time
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.lighthousecatholicmedia.org"
                target="_blank"
              >
                Catholic Media, Light House
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.mycatholic.com"
                target="_blank"
              >
                Catholic, My
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholicnews.com"
                target="_blank"
              >
                Catholic News
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.srol.org/assets/Adult-Faith-Formation/Prominent-Catholic-Periodicals.pdf"
                target="_blank"
              >
                Catholic Periodicals, Prominent
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.liguori.org"
                target="_blank"
              >
                Catholic Publication
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.ncregister.com/topic/pope-francis"
                target="_blank"
              >
                Catholic Register, National
              </a>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.stmichaelreno.org/"
                target="_blank"
              >
                Catholic, Saint Michael Catholic Church, Stead Nevada
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/ourladyofpeaceinhonolulu">
                Catholic Shrine Basilica of Our Lady of Peace in Honolulu Hawaii
              </Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.thecatholictelegraph.com/RK=2/RS=ypciuBU4YN77MVuYEMJNf0MVl.c-"
                target="_blank"
              >
                Catholic Telegraph
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.liguori.org/catholic-update"
                target="_blank"
              >
                Catholic Update
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.USCatholic.org"
                target="_blank"
              >
                Catholic, USA
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.catholicworldreport.com"
                target="_blank"
              >
                Catholic World Report
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.christlife.org"
                target="_blank"
              >
                Christ Life
              </a>
            </div>
           
            <div className="border-b-2">
              <Link href="/christmas-angels">Christmas Angels</Link>
            </div>
            <div className="border-b-2">
              <Link href="/cloisteredlife-directory">Cloistered Life</Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.chnetwork.org"
                target="_blank"
              >
                Coming Home Network
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.usccb.org"
                target="_blank"
              >
                Conference of Catholic Bishops USA
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/saint-marianne-cope">Cope, Marianne, Saint</Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.crisismagazine.com"
                target="_blank"
              >
                Crisis Magazine
              </a>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.franciscanmedia.org/franciscan-spirit-blog/top-catholic-magazines/"
                target="_blank"
              >
                Franciscan Media
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/gospel-of-john-movie"> Gospel of John, Movie</Link>
            </div>
            <div className="border-b-2">
              <a href="https://www.hprweb.com/" target="_blank">
                Homiletic Pastoral Review
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://insidethevatican.com/"
                target="_blank"
              >
                Inside The Vatican
              </a>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://beajesuit.org"
                target="_blank"
              >
                Jesuits, A place to become a jesuit 
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.youtube.com/@SocietyofJesus"
                target="_blank"
              >
                Jesuits, The Society of precious Holy, Blessed Jesus Christ
              </a>
            </div>
            

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://keepthefaith.org/latin-mass/"
                target="_blank"
              >
                Keep the Faith Latin Mass
              </a>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.loamagazine.org"
                target="_blank"
              >
                Loa Magazine
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.magnificat.net"
                target="_blank"
              >
                Magnificat
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/saint-mary-mazzarello">
                Mazzarello, Mary, Saint, Movie
              </Link>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://writersdepart.com/uploads/rule-of-st-benedict.pdf"
                target="_blank"
              >
                Monastery, benedictine Rule for Service
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/monastery-contemplative-life-today">
                Monastery, a look at comtemplative life today
              </Link>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.newadvent.org"
                target="_blank"
              >
                New Advent
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.newoxfordreview.org"
                target="_blank"
              >
                New Oxford Review
              </a>
            </div>
			      <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.youtube.com/watch?v=fRtBKz-48NI"
                target="_blank"
              >
                Nun, day in the life, Video Documentary
              </a>
            </div>
            {/* <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://willowy-beijinho-1d8105.netlify.app/"
                target="_blank"
              >
              Nuns and Convents, Precious List</a>
            </div> */}
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://cloisteredlife.com/directory/salt-lake-city"
                target="_blank"
              >
                Nuns, Carmelite, Utah
              </a>
            </div>
            
			 <div className="border-b-2">
              <Link href="/nuns-carmelite-slc-utah">Nuns, Carmelite, Utah</Link>
            </div>
			 <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href=""
                target="_blank"
              >
               Nuns, Carmelite, Cloistered Life, Utah 
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/nuns-dominican-sisters-of-saint-cecilia">Nuns, Dominican Sisters of Saint Cecilia Documentary</Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://nashvilledominican.org"
                target="_blank"
              >
               Nuns, Dominican Sisters of Saint Cecilia Website 
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://nazareth.org"
                target="_blank"
              >
               Nuns, Sisters of Charity of Nazareth, Website 
              </a>
            </div>

            <div className="border-b-2">
              <Link href="/nuns-passionate">Nuns, Passionate, Cloistered life</Link>
            </div>
            <div className="border-b-2">
              <Link href="/nuns-passionate-day-in-the-life">Nuns, Passionate, Day in the Life</Link>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://passionistsnuns.org"
                target="_blank"
              >
               Nuns, Passionists in Whitesville Kentucky, website 
              </a>
            </div>
			
			  <div className="border-b-2">
              <Link href="/saint-dominic-monastery" >Nuns, Saint Dominic's Monastery Documentary</Link>
            </div>
			
			 
            <div className="border-b-2">
              <a
                className="flex flex-wrap text-blue-500"
                href="https://www.lindenopnuns.org/"
                target="_blank"
              >
                Nuns, Saint Dominic's Monastery Website  (Please submit a financial donation for incomplete projects)
              </a>
            </div>

            <div className="border-b-2">
              <Link href="/vocation-to-the-religious-life">
                Nuns, Vocation to the Religious Life
              </Link>
            </div>

           
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.osv.com/"
                target="_blank"
              >
                Our Sunday Visitor
              </a>
            </div>
            
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://fineartamerica.com/shop/canvas+prints/padre+pio?utm_source=bing&utm_medium=cpc&utm_campaign=DSA%20-%20Shop%20Pages&utm_content=Shop%20Pages&msclkid=6979599a49881ff3f6873e2ec5d1a0e7&utm_term=%2Fshop%2F"
                target="_blank"
              >
                Pio, Padre
              </a>
            </div>

            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://passionist.org/wp-content/uploads/2020/12/Diary_StudyGuide_cp.pdf"
                target="_blank"
              >
                Prayer Guide, Saint Paul of the Cross, 1720
              </a>
            </div>
            
            <div className="border-b-2">
              <Link href="/queens-funeral">
                Queen of England Funeral Procession
              </Link>
            </div>
            
            <div className="border-b-2">
              <Link href="/saint-rita-of-cascia">
                Rita, Saint of Cascia
              </Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.stmarysmessenger.com"
                target="_blank"
              >
                Saint Marys Messenger
              </a>
            </div>
            <div className="border-b-2">
              <Link href="/sister-servants-of-the-holy-spirit">
                Sister Servants of the Holy Spirit of Perpetual Adoration
              </Link>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.spiritdaily.com"
                target="_blank"
              >
                Spirit Daily
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://upfaithandfamily.com/"
                target="_blank"
              >
                Up Faith And Family
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.vaticannews.va/en.html"
                target="_blank"
              >
                Vatican News
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://thewandererpress.com/"
                target="_blank"
              >
                Wanderer Press
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.wau.org"
                target="_blank"
              >
                Word Amoung Us
              </a>
            </div>
            <div className="border-b-2">
              <a
                className="flex flex-wrap"
                href="https://www.wordonfire.org"
                target="_blank"
              >
                Word On Fire
              </a>
            </div>
          </div>


        </div> {/* grid */}
        </div>
        </div>

      </body>
    </html>
  );
}
