'use client'

import "./globals.css";

import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import { FaBars } from 'react-icons/fa';
import { GrClose } from 'react-icons/gr';
import { useMedia } from 'react-use';

// Menu
const menuItems = [
  {
    menu: 'About',
    link: '/about',
  },
  {
    menu: 'Product',
    link: '/product',
  },
  {
    menu: 'Services',
    link: '/services',
  },
  {
    menu: 'Contact Us',
    link: '/contact',
  },
];

export default function RootLayout({children}) {

  const displayMenu = () => {
    return menuItems.map((item) => (
      <Link
        key={item.menu}
        href={item.link}
        className='pb-5 hover:text-yellow md:pb-0 md:pl-6'
      >
        {item.menu}
      </Link>
    ));
  };

    const isDesktop = useMedia('(min-width: 768px)', true);
  const [open, setOpen] = useState(false);

  const toggleSidebar = () => setOpen(!open);

  return (
    <html>
      <body>
      <Head>
        <title>Next & Tailwind Sidebar</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='flex justify-between p-2 shadow-lg items-center'>
          {/* Logo */}
          <div>
            {/* <Image src={Logo} alt='Logo' width={100} height={100} /> */}
          </div>

          {/* Menu links */}
          <div className="">
            <div className='text-red'>
              {isDesktop ? (
                displayMenu()
              ) : (
                <>
                  <button
                    className='border-none bg-none'
                    onClick={() => toggleSidebar()}
                  >
                    <FaBars />
                  </button>
                  <div
                    className={
                      open
                        ? 'absolute top-0 right-0 z-50 h-screen w-3/5 bg-white shadow-md'
                        : 'hidden'
                    }
                  >
                    <div className='flex flex-col text-center'>
                      <button
                        className='mb-7 mt-7 mr-1 flex justify-end px-5 text-xl'
                        onClick={() => toggleSidebar()}
                      >
                        <GrClose />
                      </button>
                      {displayMenu()}
                    </div>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </main>
      
      <div className="grid-container- grid grid-cols-[200px_4fr] gap-4 p-4">
        <div className="bg-green-500 h-[100vh] p-4">
          <div className="" ><Link href="/menuitem1" >menu item 1</Link></div>
          <div className="" ><Link href="/menuitem2" >menu item 2</Link></div>
          <div className="" ><Link href="/menuitem3"> menu item 3</Link></div>
        </div>
        <div className="bg-blue-500 h-[100vh] p-4">{children}</div>

     </div>
      
    </body>
    </html>
  );
}