//Sidebar.js

//import { Inter } from '@next/font/google';
import Image from 'next/image';
import Link from 'next/link';

import Logo from '../images/loop.svg';

//const inter = Inter({ subsets: ['latin'] });

// Menu items
const menuItems = [
  {
    menu: 'About',
    link: '/about',
  },
  // {
  //   menu: 'Product',
  //   link: '/product',
  // },
  // {
  //   menu: 'Services',
  //   link: '/services',
  // },
  {
    menu: 'Contact Us',
    link: '/contact',
  },
];

export default function Home() {

const displayMenu = () => {
    return menuItems.map((item) => (
      <Link
        key={item.menu}
        href={item.link}
        className='pb-5 hover:text-yellow md:pb-0 md:pl-6'
      >
        {item.menu}
      </Link>
    ));
  };

  return (
    <>
      <Head>
        <title>Next & Tailwind Sidebar</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
                {/* Tailwind CSS classes added to navbar */}
        <div className='flex justify-between p-7 shadow-lg items-center'>
          {/* Logo */}
          <div>
            <Image src={Logo} alt='Logo' width={100} height={100} />
          </div>

          {/* Menu links */}
          <div className="">
            <div className='text-red'>
              {displayMenu()}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}